#!/usr/bin/env bash

set -ex

cd /autograder/source

cp /autograder/submission/* /autograder/source/Assignment.lean

~/.elan/bin/lake build autograder AutograderTests 

~/.elan/bin/lake exe autograder AutograderTests.Solution Assignment.lean
