#!/usr/bin/env bash

cd /autograder/source

cp /autograder/submission/* /autograder/source/Assignment.lean

~/.elan/bin/lake build -v autograder AutograderTests && ~/.elan/bin/lake exe autograder AutograderTests.Solution Assignment.lean
